### ISSUE TITLE
Remove `privatekey:` from the protocol specification

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_protocol#131]
@gkc says `privatekey:` is obsolete and is never used.

The objective of this ticket is to remove `privatekey:` documentation from the protocl specification and remove it from any regex patterns.

**Comment by JeremyTubongbanua** [comment]
@gkc I can pick this up this sprint PR 87

**Comment by gkc** [comment]
@JeremyTubongbanua sounds good thank you

**Comment by JeremyTubongbanua** [comment]
@XavierChanth I had a PR on this here : https://github.com/atsign-foundation/at_protocol/pull/133

feel free to overwrite or close or whatever to the branch/PR

**Comment by xavierchanth** [comment]
> @XavierChanth I had a PR on this here : #133
> 
> feel free to overwrite or close or whatever to the branch/PR

Thanks, I didn't see this until after, but I've ended up with very similar changes + some other changes I was making to other things.
