### ISSUE TITLE
Update documentation to use new lexicon

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_protocol#28]
### Is your feature request related to a problem? Please describe.

The present spec is full of `@` where we now use `at`

### Describe the solution you'd like

Replace `@ platform` with `atPlatform` etc.

**Comment by CynthiaPeter** [comment]
Hello @XavierChanth,

What page needs this edit? Thanks

**Comment by cpswan** [comment]
@CynthiaPeter https://github.com/atsign-foundation/at_protocol/blob/trunk/specification/at_protocol_specification.md is the key doc
