### ISSUE TITLE
APKAM: Spike

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_protocol#31]
### Is your feature request related to a problem? Please describe.

See atsign-foundation/at_libraries#29

### Describe the solution you'd like

See atsign-foundation/at_libraries#29 

Spike the implementation of the [initial draft design](https://github.com/atsign-foundation/at_protocol/issues/30) so that we can identify any oversights, omissions, errors etc

**Comment by gkc** [comment]
Marking urgent as this spike is required before finalizing https://github.com/atsign-foundation/at_client_sdk/issues/821

**Comment by murali-shris** [comment]
PR60 - Worked on going through design doc and preparing implementation plan.

**Comment by murali-shris** [comment]
@gkc @cpswan I was going through the IoT spec to check whether decryption in possible with private key on SIM.
But there are no such operations available for decrypting data using private key on SIM.

There is an operation compute DH. This will generate a secret key based on diffie hellman. But the public and private key used to generate the secret key must be from different key pairs.

https://www.gsma.com/iot/wp-content/uploads/2019/12/IoT.05-v1-IoT-Security-Applet-Interface-Description.pdf

**Comment by murali-shris** [comment]
Feature request for a new dart package that will move duplicate logic in onboarding flow
https://github.com/atsign-foundation/at_client_sdk/issues/1569

**Comment by murali-shris** [comment]
analysis and meeting notes
https://docs.google.com/document/d/18Ryt8dcYemn7CkBz-MbNWATpuPFCKgg0V7tuDxQZICg/edit?usp=sharing

**Comment by murali-shris** [comment]
Worked on minor changes to APKAM spec.
 test scenarios - https://docs.google.com/document/d/18Ryt8dcYemn7CkBz-MbNWATpuPFCKgg0V7tuDxQZICg/edit?usp=sharing
initial implementation tasks
https://github.com/atsign-foundation/at_server/issues/1355
https://github.com/atsign-foundation/at_server/issues/1356
https://github.com/atsign-foundation/at_server/issues/1357
https://github.com/atsign-foundation/at_libraries/issues/347
