### ISSUE TITLE
Market facing atProtocol FAQ

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_protocol#49]
Similar to https://docs.google.com/document/d/1xFga1UvIIQcwlEeO1_IEBKphP1nN5-PG628H9pMOcHU/edit

**Comment by gkc** [comment]
FYI I won't get to this until next week as in my queue it is behind https://github.com/atsign-foundation/at_server/issues/1244 and https://github.com/atsign-foundation/docs.atsign.com/issues/276 ... if anyone else has bandwidth to make progress here that'd be great

**Comment by JeremyTubongbanua** [comment]
@anthonyvprakash who is the target audience for this FAQ?

Technical or non-technical?

**Comment by anthonyvprakash** [comment]
@JeremyTubongbanua  - it will be our partners, resellers and distributors. They need to speak our language and try to sell us. Assume decently technical in this case but also sales guys.

**Comment by gkc** [comment]
No progress on this from me in the last sprint; this sprint I'm not taking any engineering tasks, my focus will be documentation

**Comment by gkc** [comment]
There's been a lot of progress made by a whole lot of people during this last sprint. @ksanty you were marshalling all of our efforts here ... can this ticket be closed?

**Comment by ksanty** [comment]
The document still needs technical review @gkc.  @anthonyvprakash and I tagged people to review, so we need to go back and see what has been completed.  There are also still some unanswered responses.  Thanks for carrying over to PR59.

**Comment by ksanty** [comment]
I believe the bulk of questions are now completed.  Going to close as this sits with Marketing now to review and deploy across the intended outlets and audiences.
