### ISSUE TITLE
ReadMe.md -- Add current build/workflow status and license badge

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_protocol#5]
A status badge shows whether a workflow is currently failing or passing. In addition	to this, it is important to show our Github BSD 3-clause License badge on all public repositories.

A common place to add the status and license badge is in the ```README.md``` at the top alongside the GitHub License.

```diff
+ ![example workflow](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg)
+ [![GitHub License](https://img.shields.io/badge/license-BSD3-blue.svg)](./LICENSE)
```

**Comment by MrHerbalizer** [comment]
Hi Tyler, can you help me locate the github/workflow directory for the repo. Would like to know the name of the workflow. This would me first contribution, so....

**Comment by TylerTrott** [comment]
Hi there, this specific repo doesn't have a workflow as it is just specifications/documentation. Feel free to add the GitHub Licence though :)

**Comment by MrHerbalizer** [comment]
OK and thank you for the quick response..:)

**Comment by MrHerbalizer** [comment]
I have added the badge.  Have checked the preview. Do share if I have positioned the badge in the right place.

**Comment by TylerTrott** [comment]
> I have added the badge. Have checked the preview. Do share if I have positioned the badge in the right place.

Reviewed and merged, thank you!
