### ISSUE TITLE
Update notify command usage

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_protocol#50]
### Is your feature request related to a problem? Please describe.

lacks detail and is out of date

### Describe the solution you'd like

At minimum explain all of the metadata and give an example of the minimum viable notify command
e.g. `notify:update:ttr:-1:@alice:foo.bar@bob:<base64-encoded-encrypted-data`

**Comment by cpswan** [comment]
Also needs to mention that on success it returns an ID rather than `success`

**Comment by gkc** [comment]
Closed by @cpswan in #53
