### ISSUE TITLE
Setup Gitbook for at_protocol repo

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_protocol#88]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Allow this repo to be editable and hosted as a Gitbook project.

### Additional context

Based on a conversation between myself and @gkc.

Minimal work needed to make this repo Gitbook ready.

**Comment by Xlin123** [comment]
@XavierChanth I think I need perms in Gitbook, I can make requests but cannot setup Github sync cause I need to edit Space settings.

**Comment by xavierchanth** [comment]
@Xlin123 sorry for the delays, you should have access now

**Comment by Xlin123** [comment]
@XavierChanth I forgot to update you on this. I couldn't figure out a way to ungroup the spec from a header and I also couldn't figure out how to remove the README. The readme stays in even if I don't include it in the SUMMARY.md. I can try removing it from the .gitbook.yaml and see if that works if you really want it gone.

**Comment by xavierchanth** [comment]
README is the home page, so create a new md file to serve as the home page on gitbook, and set README to that file in the gitbook config.

**Comment by Xlin123** [comment]
@XavierChanth I made all the changes, please review the [atProtocol space PR](https://app.gitbook.com/o/Bf7bj1PZlU306XQWDaeE/s/OKcyQuTtJmcTiYSQrNYQ/~/changes/1/atprotocol-specification/~/details) and the [Docs space PR](https://app.gitbook.com/o/Bf7bj1PZlU306XQWDaeE/s/pQPWQHMckXtXYemavYhN/~/changes/61/~/details).

**Comment by Xlin123** [comment]
@XavierChanth I archived the pr for Docs and changed the PR for the protocol one. Can you approve it so I can close the ticket?
