### ISSUE TITLE
APKAM: Onboarding Widget Updates

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_protocol#92]
Standalone Widget which can optionally be included in the onboarding widget:

```[tasklist]
### Requesting App
- [x] Input for OTP
- [x] Enroll App / Request enrollment button
- [x] Enrollment request status
```

Standalone widget for approving side

```[tasklist]
### Receiving App
- [x] List existing requests
- [x] Approve / Deny any request
- [x] Generate & Display pin
```

Blocking: https://github.com/atsign-foundation/sshnoports/issues/163

**Comment by gkc** [comment]
Added this ticket to our main project sprint planning board. Set as P0 as it needs to get started during this sprint. Needs to be estimated at planning poker.

**Comment by sitaram-kalluri** [comment]
@CurtlyCritchlow : The APKAM changes in at_client SDK are in [srk_apkam_changes](https://github.com/atsign-foundation/at_client_sdk/tree/srk_apkam_changes)

**Comment by murali-shris** [comment]
@CurtlyCritchlow please update this task with the progress

**Comment by CurtlyCritchlow** [comment]
_

**Comment by CurtlyCritchlow** [comment]
I built the APKAM Request widget but I got stuck trying connect to vip.ve.atsign.zone. The production server doesn't have the necessary code changes as yet. @sitaram-kalluri and @murali-shris are helping me get unblock.

**Comment by sitaram-kalluri** [comment]
Spent 5 SP in PR-68. 
Completed implementation of APKAM-UI for the following 
In receiving app:
- notification screen to receive the enrollment notifications
- Approve/Deny Notifications
- Generate and display OTP
In requesting app: 
- Send request for enrollment
- List enrollments.

The changes are available in https://github.com/atsign-foundation/at_widgets/tree/at_enrollment_service

**Comment by gkc** [comment]
@CurtlyCritchlow @sitaram-kalluri @murali-shris what's latest status on this?

**Comment by sitaram-kalluri** [comment]
@gkc: The demo app we have currently is functionally working:
- An enrollment screen to submit an enrollment request.
- Notifications screen which display the enrollment requests. Approve or deny the enrollment request.
- A widget to display the OTP.
- Upon approving the enrollment, on the app that has submitted the enrollment, a .atKeys file is generated with APKAM keys and user can successfully login with the APKAM .atKeys file.

**Comment by gkc** [comment]
Thank you @sitaram-kalluri 

Are these available as widgets? Is there documentation? How would I (1) build an app which handles enrollment requests (list enrollments, generate OTPs, receive enrollment request notifications and approve or deny them (2) build an app which can make an enrollment request, and complete enrollment if approved?

**Comment by sitaram-kalluri** [comment]
> Thank you @sitaram-kalluri
> 
> Are these available as widgets? Is there documentation? How would I (1) build an app which handles enrollment requests (list enrollments, generate OTPs, receive enrollment request notifications and approve or deny them (2) build an app which can make an enrollment request, and complete enrollment if approved?

@gkc: Yes, the above functionality is available as widgets. Updated the README of the at_enrollment_app package on how to use it.

Attaching the README link here:[README](https://github.com/atsign-foundation/at_widgets/blob/at_enrollment_app/packages/at_enrollment_service/README.md)

**Comment by gkc** [comment]
Thanks @sitaram-kalluri

**Comment by sitaram-kalluri** [comment]
Attaching the screenshots of the the demo app developed for enrollment service

<details>

<summary> Screenshots of the demo enrollment service </summary>

![home_page_1](https://github.com/atsign-foundation/at_protocol/assets/16645698/01f0f161-2d33-41fb-a48c-0ed07c739f25)
![home_screen](https://github.com/atsign-foundation/at_protocol/assets/16645698/1faa8e8d-edeb-4fcf-a0ac-3a2bc7360f3f)
![receive_enrollment_request](https://github.com/atsign-foundation/at_protocol/assets/16645698/3c4e8706-6a01-4dd7-9325-ba5237cf955f)
![send_enrollment_screen](https://github.com/atsign-foundation/at_protocol/assets/16645698/e7568500-8379-4eaa-a67b-ce19bc8cc955)

</details>

**Comment by ksanty** [comment]
@sachins-geekyants @Sardar1208 tasks to be defined for the apps team. @murali-shris will clarify further

**Comment by Sardar1208** [comment]
@sachins-geekyants Has completed the the UI according to the design. Currently working on the integration of services.
Minor blocker due to unsupported feature on iOS

**Comment by Sardar1208** [comment]
Reducing to 6 SP and moving to next sprint

**Comment by Sardar1208** [comment]
Needs more work. Keeping the 6SP and moving to next sprint

**Comment by Sardar1208** [comment]
Needs more work
moving to next sprint.

**Comment by sachins-geekyants** [comment]
apkam keychain store migrated from `flutter_secure_storage` to `biometric_storage` : [apkam_onboarding_biometric_storage](https://github.com/atsign-foundation/at_client_sdk/tree/apkam_onboarding_biometric_storage)

**Comment by sachins-geekyants** [comment]
Currently, we have two dependencies on sdk
-  [encryptedAPKAMSymmetric key is missed when the pending enrollments are fetched](https://github.com/atsign-foundation/at_server/issues/1821)

- on enrollment approval, there is no way of knowing the path where atKey have been saved

cc: @sitaram-kalluri

**Comment by sitaram-kalluri** [comment]
> Currently, we have two dependencies on sdk
> 
>     * [encryptedAPKAMSymmetric key is missed when the pending enrollments are fetched](https://github.com/atsign-foundation/at_server/issues/1821)
> 
>     * on enrollment approval, there is no way of knowing the path where atKey have been saved
> 
> 
> cc: @sitaram-kalluri

[encryptedAPKAMSymmetric key is missed when the pending enrollments are fetched](https://github.com/atsign-foundation/at_server/issues/1821) : This is completed and changes are deployed to canary.

We are working on 2nd issue.

**Comment by gkc** [comment]
@sitaram-kalluri Have you done sanity testing with any of the canary atSigns? If it's safe to promote this from canary to prod then we should do that without much delay.

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri Have you done sanity testing with any of the canary atSigns? If it's safe to promote this from canary to prod then we should do that without much delay.

@gkc : Purnima is running sanity tests on the canary atSigns.

**Comment by sitaram-kalluri** [comment]
> Currently, we have two dependencies on sdk
> 
>     * [encryptedAPKAMSymmetric key is missed when the pending enrollments are fetched](https://github.com/atsign-foundation/at_server/issues/1821)
> 
>     * on enrollment approval, there is no way of knowing the path where atKey have been saved
> 
> 
> cc: @sitaram-kalluri

The second issue is addressed in the PR: https://github.com/atsign-foundation/at_client_sdk/pull/1257

**Comment by sachins-geekyants** [comment]
We have a working version of enrollment package.

Work that still needs to be done
```
- fetchPendingEnrollments gives denied/approved requests.
- use the generated atkey to automatically onboard
- docs
```

**Comment by sitaram-kalluri** [comment]
We have a working version of enrollment demo app which is available in the following branch: https://github.com/atsign-foundation/at_widgets/tree/enrollment_screens .

Pending work is to merge the changes into trunk branch and publish the packages. We have a tracker ticket on the pending action items: https://github.com/atsign-foundation/operations/issues/88

Closing this ticket here.
